project:
  type: website
  output-dir: docs/ # I added this 3/2, do I need it? 

website:
  title: "Maiko's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    code-fold: true # added 3/2
    code: false # added 3/2
    theme:
      - minty
      - brand
    css: styles.css
execute: 
    warning: false
    message: false 
editor: visual

