project:
  type: website
  output-dir: docs/ 

website:
  title: "Maiko's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    code-fold: true 
    code: false
    theme:
      - minty
      - brand
    css: styles.css
execute: 
    warning: false
    message: false 
editor: visual

